
language: c

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: COMPILER=gcc
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
      env: COMPILER=clang
    - os: osx
      osx_image: xcode8.2
      compiler: clang
      env: COMPILER=clang

script:
  #- cd examples
  #- gcc -std=c99 -Wall -o test test.c ../src/iniparser.c ../src/internal/ini.c -I../src
  #- ./test
  - mkdir build && cd build
  - cmake .. && make && sudo make install
  - cd examples && ./mytest

notifications:
  email: false